config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin', :constraints => AdminConstraint.new
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :outings do 
    resources :actions
  end
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/action.rb
class Action < ApplicationRecord
    has_many :actions_outings
    has_many :outings, through: :actions_outings
    # scope :location, -> (location) { where("location ILIKE ?", "%#{location}%") }
end

app/models/actions_outing.rb
class ActionsOuting < ApplicationRecord
    belongs_to :outing
    belongs_to :action
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/outing.rb
class Outing < ApplicationRecord
    validates :date, presence: true
    validates :start_time, presence: true
    validates :end_time, presence: true
    
    has_many :actions_outings
    has_many :actions, through: :actions_outings
    # has_and_belongs_to_many :users, :join_table => "outings_users", :class_name => "OutingUser"
    has_many :outings_users
    has_many :users, through: :outings_users
end

app/models/outings_user.rb
class OutingsUser < ApplicationRecord
    belongs_to :outing
    belongs_to :user
end  

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

  has_many :outings_users, dependent: :destroy
  has_many :outings, through: :outings_users

  enum roles: [:user, :contributor, :admin]
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
    def index

        @outing = Outing.find(params[:outing_id])
        # @actions = Action.all
        # @actions = @actions.where("lower(location) LIKE ?", "%#{params[:location].downcase}%") if params[:location]
        if params[:location]
            @actions = Action.where("lower(location) LIKE ?", "%#{params[:location].downcase}%")
        else
            @actions = Action.all
        end
    end
    
    def new
    end
    
    def create
        @outing = Outing.find(params[:outing_id])
        actions_outing = ActionsOuting.new(outing_action_params)
        if actions_outing.save
            redirect_to outing_actions_path(@outing.id), method: :get
            flash[:success] = "Your action was saved successfully."
        else
            flash[:danger] = "Please try again."
        end
    end
    
    def show
        @action = Action.location(params[:location]) if params[:location].present?
    end
    
    def edit
    end

    def update
    end

    def destroy
        @actions_outing = ActionsOuting.where(outing_id: params[:outing_id]).find_by(action_id: params[:id])
        if @actions_outing.destroy
            redirect_to outing_path(params[:outing_id])
            flash[:success] = "Your action was deleted successfully."
        else
            redirect_to outing_path(params[:outing_id])
            flash[:danger] = "Please try again."
        end
    end

    private

    def outing_action_params
        params.permit(:outing_id, :action_id)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/outings_controller.rb
class OutingsController < ApplicationController
    def index
        @outings = User.find(current_user.id).outings
    end

    def new
        @outing = Outing.new
    end

    def create
        @outing = Outing.new(outing_params)
        
        if @outing.save
            OutingsUser.create(user_id: current_user.id, outing_id: @outing.id)
            flash[:message] = "Saved!"
            message = 'You have created an outing on GoMana! Log in and check it out now.'
            WhatsappJob.perform_now(message)
            redirect_to root_path
        else
            flash[:message] = "Try again!"
            render new
        end
    end

    def show
        @outing = Outing.find(params[:id])
    end

    def edit

    end

    def update
    end

    def destroy

    end

    private
    
    def outing_params
        params.require(:outing).permit(:date, :start_time, :end_time)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
      flash[:success] = "Logged in!"
    else
      flash[:danger] = "Email or password is invalid."
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
    flash[:success] = "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/outings_helper.rb
module OutingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/actions/_index.html.erb
<div class="row">
    <% @actions.each do |x| %>
        <% unless @outing.actions.exists?(x.id) %>
            <div class="col-sm-3">
                <div class="card">
                <div class="card-body">
                    <b>Action ID:</b> <%= x.id %><br>
                    <b>Name:</b> <%= x.name %><br>
                    <b>Description:</b> <%= x.description %><br>
                    <b>Location:</b> <%= x.location %><br>
                    <%= form_with url: outing_actions_path, local: true do |f| %>
                        <%= f.hidden_field :outing_id, value: @outing.id %>
                        <%= f.hidden_field :action_id, value: x.id %>
                        <%= f.submit "Add" %>
                    <% end %>
                </div>
                </div>
            </div>
        <% end %>
    <%end%>
</div>

app/views/actions/index.html.erb
<h1 class="display-4 text-center">Add Action to Outing</h1>

<p>Outing ID: <%= @outing.id %></p>

<div id='action-search-box' style='margin-bottom:20px'>
    Search for Location: 
    <%= form_with url: outing_actions_path, method: :get, remote: true do |form| %>
        <%= form.text_field :location, placeholder: "Location", list: "location_name" %>
        <%= form.submit "Submit"%>
    <% end %>
</div>

<div id='action-container'>
    <%= render partial: 'index' %>
</div>

app/views/actions/index.js.erb
$(document).ready(function(){
    $('#action-container').html("<%= j render('index') %>")
});

app/views/actions/show.html.erb
<h1>Add action to outing</h1>

<p>Outing ID: <%= @outing.id %></p>

        Action ID: <%= @action.id %><br>
        <%= @action.name %><br>
        <%= @action.description %><br>
        <%= @action.location %><br>
        <%= form_with url: outing_actions_path, local: true do |f| %>
            <%= f.hidden_field :outing_id, value: @outing.id %>
            <%= f.hidden_field :action_id, value: @action.id %>
            <%= f.submit "Add" %>
        <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoMana</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="<%=root_path%>">
          <img src="https://getbootstrap.com/docs/4.3/assets/brand/bootstrap-solid.svg" width="30" height="30" alt="">
        </a>
        <a class="navbar-brand" href="<%=root_path%>">GoMana</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <ul class="nav navbar-nav ml-auto">
            <% if current_user %>
              <li><%= link_to "Add Outing", new_outing_path, :class=>"nav-item nav-link" %></li>
              <li><%= link_to "My Outings", outings_path, :class=>"nav-item nav-link" %></li>
              <% if current_user.admin? %>
                <li><%= link_to "Admin Dashboard", rails_admin_path, :class=>"nav-item nav-link" %></li>
              <% end %>
              <li><%= link_to "Log Out", logout_path, :class=>"nav-item nav-link" %></li>
            <% else %>
              <li><%= link_to "Sign Up", signup_path, :class=>"nav-item nav-link" %></li>
              <li><%= link_to "Log In", login_path, :class=>"nav-item nav-link" %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <% flash.each do |key, value| %>
      <div class = "alert alert-<%=key%>">
        <%= value %>
      </div>
    <%end%>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  </body>
</html>

app/views/outings/index.html.erb
<div class="container text-center">
    <h1 class="display-4 text-center">Outing List</h1>
        <div class="row">
        <% @outings.each do |x| %>
            <div class="col-sm-3">
                <div class="card">
                <div class="card-body">
                    Outing ID: <%= x.id %> <br>
                    Date: <%= x.date %> <br>
                    Start Time: <%= x.start_time.to_s(:time) %> <br>
                    End Time: <%= x.end_time.to_s(:time) %> <br>
                    Duration: <%=  (x.end_time - x.start_time).to_f/60 %> mins <br>
                    <%= link_to "Show More", outing_path(x.id), method: :get, :class => "btn btn-outline-success my-2 my-sm-0" %>
                </div>
                </div>
            </div>
        <%end%>
    </div>
</div>

app/views/outings/new.html.erb
<div class="container card" style="width: 30rem;">
  <div class="card-body">
    <p id="alert"><%= alert %></p>
    <h1 class="display-4 text-center">New Outing</h1>
      <%= form_with model: @outing, local: true do |form| %>
        <div class="field">
          <%= form.label :date %>
          <%= form.date_field :date, :class => "form-control" %>
        </div>
        <div class="field">
          <%= form.label :start_time %>
          <%= form.time_field :start_time, :class => "form-control" %>
        </div>
        <div class="field">
          <%= form.label :end_time %>
          <%= form.time_field :end_time, :class => "form-control" %>
        </div>
        <div class="actions" style="margin-top: 20px">
          <%= form.submit "Submit", :class => "form-control btn btn-outline-success my-2 my-sm-0" %>
        </div>
      <% end %>
  </div>
</div>

app/views/outings/show.html.erb
<h1 class="display-4 text-center">View Outing</h1>

<div class="container card text-center">
    <div class="card-body">
        Outing ID: <%= @outing.id %> <br>
        Date: <%= @outing.date %> <br>
        Start Time: <%= @outing.start_time.to_s(:time) %> <br>
        End Time: <%= @outing.end_time.to_s(:time) %> <br>
        Duration: <%=  (@outing.end_time - @outing.start_time).to_f/60 %> mins <br>
        <%= link_to "Add Action", outing_actions_path(@outing.id), method: :get, :class => "btn btn-outline-success my-2 my-sm-0" %>
    </div>
    </div>
<p>

<h1 class="display-4 text-center">Current Actions</h1>

<div class="row">
    <% @outing.actions.each do |x| %>
        <div class="col-sm-3">
            <div class="card">
            <div class="card-body">
                <%= x.id %><br>
                <%= x.name %><br>
                <%= x.description %><br>
                <%= x.location %><br>
                <%= link_to "Delete", outing_action_path(@outing.id, x.id), method: :delete, data: {confirm: 'Are you sure you want to delete this action?'}%>
            </div>
            </div>
        </div>
    <%end%>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class= "avatar-field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar, :class => "form-control btn btn-outline-light my-2 my-sm-0"%>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, :class => "form-control" %>
  </div>
  
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, :class => "form-control" %>
  </div>

  <div class="actions" style="margin-top: 20px">
    <%= form.submit :class => "form-control btn btn-outline-success my-2 my-sm-0" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container card" style="width: 30rem;">
  <div class="card-body">
    <p id="alert"><%= alert %></p>
    <h1 class="display-4 text-center">New User</h1>
        <%= render 'form', user: @user %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">GoMana</h1>
  <p class="lead">Where will your next outing be?</p>
  <hr class="my-4">
  <p>Lighten up, just enjoy life, smile more, laugh more, and don't get so worked up about things.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>